version: '3'

services:
  snippet-manager:
    container_name: "snippet-manager"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
        NEW_RELIC_APP_NAME: ${NEW_RELIC_APP_NAME}
    environment:
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
      NEW_RELIC_APP_NAME: ${NEW_RELIC_APP_NAME}
    ports:
      - "49160:4322"
    volumes:
      - ./data:/app/data
    depends_on:
      - api
      - postgres
    env_file:
      - .env
  postgres:
    container_name: "manager-db"
    image: postgres:alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    expose:
      - "5432"

  api:
    container_name: "asset_service"
    image: ghcr.io/austral-ingsis/snippet-asset-service:latest
    ports:
      - "8081:8080"
    environment:
      AZURE_HOST: "http://azurite"
      NEW_RELIC_APP_NAME: "asset service"
      NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
    env_file:
      - .env


  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: "azurite"
    hostname: azurite
    restart: always
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - blob:/workspace

  snippet-permission:
    container_name: "snippet-permission"
    image: ghcr.io/ingsis-group-4/snippet-permission-dev:latest
    ports:
      - "8080:8080"
    environment:
      DB_USERNAME: ${PERMISSION_POSTGRES_USER}
      DB_PASSWORD: ${PERMISSION_POSTGRES_PASSWORD}
      DB_NAME: ${PERMISSION_POSTGRES_DB}
      DB_HOST: ${PERMISSION_DB_HOST}
      DB_PORT: ${PERMISSION_DB_PORT}
    env_file:
      - .env
    depends_on:
      - permissions-db
    expose:
      - "8080"

  permissions-db:
    container_name: "permissions-db"
    image: postgres:latest
    environment:
      POSTGRES_DB: ${PERMISSION_POSTGRES_DB}
      POSTGRES_USER: ${PERMISSION_POSTGRES_USER}
      POSTGRES_PASSWORD: ${PERMISSION_POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - permissions-db:/var/lib/postgresql/data
    env_file:
      - .env
    expose:
      - "5432"

volumes:
  blob:
    external: false
  postgres-data:
  permissions-db:

