name: "Continuous Deployment to dev"
on:
  workflow_dispatch: 
  push:
    branches:
      - dev

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages and Upload it to the server 
    runs-on: ubuntu-latest
    steps:
      - name: Create Short SHA
        uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
          length: 8

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GitHub Packages
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/ingsis-group-4/snippet-manager-dev:${{ steps.short-sha.outputs.sha }}
            ghcr.io/ingsis-group-4/snippet-manager-dev:latest

          build-args: |
            NEW_RELIC_LICENSE_KEY=${{ secrets.NEW_RELIC_LICENSE_KEY }}
            NEW_RELIC_APP_NAME=${{ secrets.NEW_RELIC_APP_NAME }}
           
      - name: Update server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_URL }}
          username: "snippet-searcher-admin"
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd snippet-infra
            docker compose -f docker-compose.dev.yml stop snippet-manager
            docker compose -f docker-compose.dev.yml up snippet-manager -d --build
