name: "Continuous Deployment to dev"
on:
  workflow_dispatch: {}
  push:
    branches:
      - dev
      - automate-deploy-v2

jobs:
#  push_to_registry:
#    name: Push Docker image to GitHub Packages
#    runs-on: ubuntu-latest
#    steps:
#      - name: Create Short SHA
#        uses: benjlevesque/short-sha@v1.2
#        id: short-sha
#        with:
#          length: 8
#
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v2
#
#      - name: Login to GitHub Container Registry
#        uses: docker/login-action@v1
#        with:
#          registry: ghcr.io
#          username: ${{ github.repository_owner }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#
#      - name: Push to GitHub Packages
#        id: docker_build
#        uses: docker/build-push-action@v4
#        with:
#          push: true
#          platforms: linux/amd64,linux/arm64
#          tags: |
#            ghcr.io/ingsis-group-4/snippet-manager-dev:${{ steps.short-sha.outputs.sha }}
#            ghcr.io/ingsis-group-4/snippet-manager-dev:latest
  dummy_job:
      name: Dummy job
      runs-on: ubuntu-latest
      steps:
        - name: Dummy step
          run: echo "Dummy step"

  deploy_to_dev:
    name: Deploy to dev
#    needs: push_to_registry
    uses: Ingsis-Group-4/common-actions/.github/workflows/deploy.yml@main
    with:
      container_name: snippet-manager
      docker_compose_file: docker-compose.dev.yml
    secrets:
      server_url: ${{ secrets.DEV_URL }}
      ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
