name: "Continuous Deployment to dev"
on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Create Short SHA
        uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
          length: 8

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GitHub Packages
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/ingsis-group-4/snippet-manager-dev:${{ steps.short-sha.outputs.sha }}
            ghcr.io/ingsis-group-4/snippet-manager-dev:latest

  deploy_to_dev:
    name: Deploy to dev
    needs: push_to_registry
    uses: Ingsis-Group-4/common-actions/.github/workflows/deploy.yml@main
    with:
      server_url: ${{ secrets.DEV_URL }}
      container_name: snippet-manager
      docker_compose_file: docker-compose.dev.yml
    secrets:
      DEV_URL: ${{ secrets.DEV_URL }}
