# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main", "dev", "ci-common-actions" ]
  pull_request:
    branches: [ "main", "dev" ]


jobs:
  build:
    runs-on: ubuntu-latest

    uses: Ingsis-Group-4/common-actions/.github/workflows/ci.yaml@common-ci
    with:
      github_token: ${{ secrets.GITHUB_TOKEN }}
